/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TimeEntry } from '../types';
import { DEFAULT_CATEGORIES } from './categories';

export function getSeededData(currentDateStrStr: string = '2026-05-23'): TimeEntry[] {
  const baseDate = new Date(currentDateStrStr);
  const formatDateAtHour = (daysOffset: number, hours: number, minutes: number): string => {
    const d = new Date(baseDate);
    d.setDate(baseDate.getDate() + daysOffset);
    d.setHours(hours, minutes, 0, 0);
    return d.toISOString();
  };

  const getCategory = (id: string) => {
    const cat = DEFAULT_CATEGORIES.find(c => c.id === id);
    return cat || DEFAULT_CATEGORIES[DEFAULT_CATEGORIES.length - 1];
  };

  const entries: TimeEntry[] = [
    // --- TODAY (Day 0) ---
    {
      id: 'today-1',
      title: 'تنقل بالسيارة إلى مقر عمل العميل',
      category_id: 'transit',
      start_time: formatDateAtHour(0, 7, 30),
      end_time: formatDateAtHour(0, 8, 15),
      duration_minutes: 45,
      note: 'زحمة خفيفة في الطريق الدائري',
      icon: getCategory('transit').icon,
      color: getCategory('transit').color,
      created_at: formatDateAtHour(0, 8, 15),
      updated_at: formatDateAtHour(0, 8, 15),
    },
    {
      id: 'today-2',
      title: 'برمجة وإصلاح ثغرات قاعدة البيانات',
      category_id: 'work',
      start_time: formatDateAtHour(0, 8, 15),
      end_time: formatDateAtHour(0, 11, 30),
      duration_minutes: 195,
      note: 'جلسة تركيز عميق قوية، تم حل مشكلة الـ queries المتكررة واستقرار الـ Docker',
      usefulness_status: 'useful',
      icon: getCategory('work').icon,
      color: getCategory('work').color,
      created_at: formatDateAtHour(0, 11, 30),
      updated_at: formatDateAtHour(0, 11, 30),
    },
    {
      id: 'today-3',
      title: 'استراحة قهوة الصباح',
      category_id: 'break',
      start_time: formatDateAtHour(0, 11, 30),
      end_time: formatDateAtHour(0, 11, 55),
      duration_minutes: 25,
      note: 'كورتادو لذيذ مع زملائي ونقاش حول كرة القدم',
      usefulness_status: 'useful',
      icon: getCategory('break').icon,
      color: getCategory('break').color,
      created_at: formatDateAtHour(0, 11, 55),
      updated_at: formatDateAtHour(0, 11, 55),
    },
    {
      id: 'today-4',
      title: 'اجتماع التخطيط الأسبوعي للفريق',
      category_id: 'meetings',
      start_time: formatDateAtHour(0, 12, 0),
      end_time: formatDateAtHour(0, 13, 10),
      duration_minutes: 70,
      note: 'مراجعة أهداف الربع الثاني ومشاركة التحديثات',
      usefulness_status: 'useful',
      icon: getCategory('meetings').icon,
      color: getCategory('meetings').color,
      created_at: formatDateAtHour(0, 13, 10),
      updated_at: formatDateAtHour(0, 13, 10),
    },
    // GAP HERE FROM 13:10 to 14:30 (representing 1h 20m Untracked Time)
    {
      id: 'today-5',
      title: 'تصفح تويتر وانستغرام بلا وعي',
      category_id: 'social',
      start_time: formatDateAtHour(0, 14, 30),
      end_time: formatDateAtHour(0, 15, 45),
      duration_minutes: 75,
      note: 'ضياع وقت كبير جداً بسبب سكرول الريلز والترندات.. أحتاج لوضع حد للتطبيقات',
      usefulness_status: 'not_useful',
      icon: getCategory('social').icon,
      color: getCategory('social').color,
      created_at: formatDateAtHour(0, 15, 45),
      updated_at: formatDateAtHour(0, 15, 45),
    },
    {
      id: 'today-6',
      title: 'تدريب هاردكور الجزء العلوي من الجسم',
      category_id: 'sport',
      start_time: formatDateAtHour(0, 17, 30),
      end_time: formatDateAtHour(0, 18, 45),
      duration_minutes: 75,
      note: 'تمرين ممتاز جداً، زيادة في الأوزان وطاقة عالية اليوم',
      usefulness_status: 'useful',
      icon: getCategory('sport').icon,
      color: getCategory('sport').color,
      created_at: formatDateAtHour(0, 18, 45),
      updated_at: formatDateAtHour(0, 18, 45),
    },
    {
      id: 'today-7',
      title: 'متابعة كورس اللغة الإسبانية وعالم الدويولينجو',
      category_id: 'language',
      start_time: formatDateAtHour(0, 20, 0),
      end_time: formatDateAtHour(0, 20, 45),
      duration_minutes: 45,
      note: 'تعلم أهم العبارات المستخدمة في السفر والمطاعم',
      usefulness_status: 'useful',
      icon: getCategory('language').icon,
      color: getCategory('language').color,
      created_at: formatDateAtHour(0, 20, 45),
      updated_at: formatDateAtHour(0, 20, 45),
    },
    {
      id: 'today-8',
      title: 'مشاهدة مقاطع يوتيوب عشوائية عن الذكاء الاصطناعي',
      category_id: 'youtube',
      start_time: formatDateAtHour(0, 21, 30),
      end_time: formatDateAtHour(0, 23, 0),
      duration_minutes: 90,
      note: 'بعض المقاطع كانت مثيرة ولكن الوقت طويل وكان من الأفضل القراءة',
      usefulness_status: 'not_useful',
      icon: getCategory('youtube').icon,
      color: getCategory('youtube').color,
      created_at: formatDateAtHour(0, 23, 0),
      updated_at: formatDateAtHour(0, 23, 0),
    },

    // --- YESTERDAY (Day -1) ---
    {
      id: 'yesterday-1',
      title: 'كتابة المستندات التقنية للمشروع الجديد',
      category_id: 'work',
      start_time: formatDateAtHour(-1, 9, 0),
      end_time: formatDateAtHour(-1, 12, 0),
      duration_minutes: 180,
      note: 'شرح معمق للـ Architecture والمخططات الهيكلية',
      usefulness_status: 'useful',
      icon: getCategory('work').icon,
      color: getCategory('work').color,
      created_at: formatDateAtHour(-1, 12, 0),
      updated_at: formatDateAtHour(-1, 12, 0),
    },
    {
      id: 'yesterday-2',
      title: 'إعداد وجبة غداء صحية وتناولها',
      category_id: 'cooking',
      start_time: formatDateAtHour(-1, 12, 30),
      end_time: formatDateAtHour(-1, 13, 40),
      duration_minutes: 70,
      note: 'صدور دجاج متبلة مع أرز بسمتي وخضار مشوي',
      usefulness_status: 'useful',
      icon: getCategory('cooking').icon,
      color: getCategory('cooking').color,
      created_at: formatDateAtHour(-1, 13, 40),
      updated_at: formatDateAtHour(-1, 13, 40),
    },
    {
      id: 'yesterday-3',
      title: 'تصفح ريلز انستغرام وتويتر تريندز',
      category_id: 'social',
      start_time: formatDateAtHour(-1, 14, 0),
      end_time: formatDateAtHour(-1, 15, 30),
      duration_minutes: 90,
      note: 'مشتت وسيء للغاية.. أحتاج لتثبيت موانع تشتت',
      usefulness_status: 'not_useful',
      icon: getCategory('social').icon,
      color: getCategory('social').color,
      created_at: formatDateAtHour(-1, 15, 30),
      updated_at: formatDateAtHour(-1, 15, 30),
    },
    {
      id: 'yesterday-4',
      title: 'قراءة كتاب "العادات الذرية" لجيمس كلير',
      category_id: 'reading',
      start_time: formatDateAtHour(-1, 16, 0),
      end_time: formatDateAtHour(-1, 17, 30),
      duration_minutes: 90,
      note: 'فصل القوانين الأربعة لتكوين العادة.. كتاب مذهل فعلاً ومحفز للأداء',
      usefulness_status: 'useful',
      icon: getCategory('reading').icon,
      color: getCategory('reading').color,
      created_at: formatDateAtHour(-1, 17, 30),
      updated_at: formatDateAtHour(-1, 17, 30),
    },
    {
      id: 'yesterday-5',
      title: 'رياضة الهيت وحرق السعرات بالمنزل',
      category_id: 'sport',
      start_time: formatDateAtHour(-1, 18, 0),
      end_time: formatDateAtHour(-1, 19, 0),
      duration_minutes: 60,
      note: 'كارديو مكثف وتعرق كامل لتخفيف التوتر الدماغي',
      usefulness_status: 'useful',
      icon: getCategory('sport').icon,
      color: getCategory('sport').color,
      created_at: formatDateAtHour(-1, 19, 0),
      updated_at: formatDateAtHour(-1, 19, 0),
    },

    // --- DAY -2 ---
    {
      id: 'day2-1',
      title: 'مراجعة طلبات السحب للبرمجيات Code Review',
      category_id: 'work',
      start_time: formatDateAtHour(-2, 10, 0),
      end_time: formatDateAtHour(-2, 12, 30),
      duration_minutes: 150,
      note: 'التدقيق في مشاكل الخصوصية والأداء وحفظ الكود للمهندس الجديد',
      usefulness_status: 'useful',
      icon: getCategory('work').icon,
      color: getCategory('work').color,
      created_at: formatDateAtHour(-2, 12, 30),
      updated_at: formatDateAtHour(-2, 12, 30),
    },
    {
      id: 'day2-2',
      title: 'ممارسة الألعاب مع الأصدقاء على بلايستيشن',
      category_id: 'entertainment',
      start_time: formatDateAtHour(-2, 15, 0),
      end_time: formatDateAtHour(-2, 17, 0),
      duration_minutes: 120,
      note: 'ترويح جيد عن النفس ونقاش وسوالف جميلة',
      usefulness_status: 'not_useful',
      icon: getCategory('entertainment').icon,
      color: getCategory('entertainment').color,
      created_at: formatDateAtHour(-2, 17, 0),
      updated_at: formatDateAtHour(-2, 17, 0),
    },
    {
      id: 'day2-3',
      title: 'تصفح مشتت لشرتات اليوتيوب والتعليقات السلبية',
      category_id: 'youtube',
      start_time: formatDateAtHour(-2, 19, 0),
      end_time: formatDateAtHour(-2, 21, 0),
      duration_minutes: 120,
      note: 'أحد أطول الفترات عديمة الفائدة اليوم.. الترفيه اللانهائي مسمم ومحبط',
      usefulness_status: 'not_useful',
      icon: getCategory('youtube').icon,
      color: getCategory('youtube').color,
      created_at: formatDateAtHour(-2, 21, 0),
      updated_at: formatDateAtHour(-2, 21, 0),
    },

    // --- DAY -3 ---
    {
      id: 'day3-1',
      title: 'التخطيط وتوزيع المهام على الجانت شارت الأساسية',
      category_id: 'work',
      start_time: formatDateAtHour(-3, 8, 30),
      end_time: formatDateAtHour(-3, 11, 30),
      duration_minutes: 180,
      note: 'تحديد مهام الربع وهيكلة الجدول الزمني بدقة متناهية',
      usefulness_status: 'useful',
      icon: getCategory('work').icon,
      color: getCategory('work').color,
      created_at: formatDateAtHour(-3, 11, 30),
      updated_at: formatDateAtHour(-3, 11, 30),
    },
    {
      id: 'day3-2',
      title: 'قراءة رواية ممتعة باللغة الجديدة',
      category_id: 'reading',
      start_time: formatDateAtHour(-3, 14, 0),
      end_time: formatDateAtHour(-3, 15, 15),
      duration_minutes: 75,
      note: 'فصلين من كتاب ممتع وهادئ تحت المطر',
      usefulness_status: 'useful',
      icon: getCategory('reading').icon,
      color: getCategory('reading').color,
      created_at: formatDateAtHour(-3, 15, 15),
      updated_at: formatDateAtHour(-3, 15, 15),
    },
    {
      id: 'day3-3',
      title: 'مكالمات فيديو مطولة مع العائلة والأقارب للاطمئنان',
      category_id: 'calls',
      start_time: formatDateAtHour(-3, 16, 0),
      end_time: formatDateAtHour(-3, 17, 30),
      duration_minutes: 90,
      note: 'صلة رحم وشعور دافئ، وقت رائع وضروري للتواصل',
      usefulness_status: 'useful',
      icon: getCategory('calls').icon,
      color: getCategory('calls').color,
      created_at: formatDateAtHour(-3, 17, 30),
      updated_at: formatDateAtHour(-3, 17, 30),
    },

    // --- DAY -4 ---
    {
      id: 'day4-1',
      title: 'عملية تفعيل السيرفرات وإطلاق النظام للجمهور',
      category_id: 'work',
      start_time: formatDateAtHour(-4, 9, 0),
      end_time: formatDateAtHour(-4, 15, 0),
      duration_minutes: 360,
      note: 'إطلاق حاسم وناجح للموقع الإلكتروني الجديد ولا يوجد أعطال تذكر',
      usefulness_status: 'useful',
      icon: getCategory('work').icon,
      color: getCategory('work').color,
      created_at: formatDateAtHour(-4, 15, 0),
      updated_at: formatDateAtHour(-4, 15, 0),
    },
    {
      id: 'day4-2',
      title: 'سوشيال ميديا ونقاشات ترند تويتر غير البناءة',
      category_id: 'social',
      start_time: formatDateAtHour(-4, 16, 30),
      end_time: formatDateAtHour(-4, 18, 0),
      duration_minutes: 90,
      note: 'النقاشات لا تفيد وأرهقت عقلي بلا فائدة كبرى',
      usefulness_status: 'not_useful',
      icon: getCategory('social').icon,
      color: getCategory('social').color,
      created_at: formatDateAtHour(-4, 18, 0),
      updated_at: formatDateAtHour(-4, 18, 0),
    },

    // --- DAY -5 ---
    {
      id: 'day5-1',
      title: 'جلسة تدريب مكثفة وتمارين حرق الدهون بالجري',
      category_id: 'sport',
      start_time: formatDateAtHour(-5, 7, 0),
      end_time: formatDateAtHour(-5, 8, 30),
      duration_minutes: 90,
      note: 'جري بالحديقة وصعود المرتفعات الخفيفة',
      usefulness_status: 'useful',
      icon: getCategory('sport').icon,
      color: getCategory('sport').color,
      created_at: formatDateAtHour(-5, 8, 30),
      updated_at: formatDateAtHour(-5, 8, 30),
    },
    {
      id: 'day5-2',
      title: 'كتابة وتعديل وثيقة المتطلبات البرمجية PRD',
      category_id: 'work',
      start_time: formatDateAtHour(-5, 9, 0),
      end_time: formatDateAtHour(-5, 13, 0),
      duration_minutes: 240,
      note: 'جلسة ثرية للغاية مع مدير المنتج لضبط زوايا العمل والتقاطعات السحابية',
      usefulness_status: 'useful',
      icon: getCategory('work').icon,
      color: getCategory('work').color,
      created_at: formatDateAtHour(-5, 13, 0),
      updated_at: formatDateAtHour(-5, 13, 0),
    },
    {
      id: 'day5-3',
      title: 'استراحة وتأمل واسترخاء العضلات الذهنية',
      category_id: 'meditation',
      start_time: formatDateAtHour(-5, 14, 0),
      end_time: formatDateAtHour(-5, 14, 45),
      duration_minutes: 45,
      note: 'تمرين تنفس عميق وصمت تام مفيد جداً لإستعادة الشغف وراحة العينين',
      usefulness_status: 'useful',
      icon: getCategory('meditation').icon,
      color: getCategory('meditation').color,
      created_at: formatDateAtHour(-5, 14, 45),
      updated_at: formatDateAtHour(-5, 14, 45),
    }
  ];

  return entries;
}
